apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service-deployment
  labels:
    app: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - name: security-service-container
          image: ${{ secrets.DOCKERHUB_USERNAME }}/nila_secure:${{ github.sha }}
          ports:
            - containerPort: 8000  # Adjust if your app uses a different port
          envFrom:
            - secretRef:
                name: security-service-secrets
