apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  type: LoadBalancer
  selector:
    app: security-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Adjust to match your application's port
